Fixed dealing with readonly files.
Script would crash when a file in AccuRev was set as read only. 

PermissionError: [WinError 5] Access is denied: 'D:\\path\\to\\readonly\\file.txst'

This change catches the exception and then removes the readonly flag, and tries to delete the file a second time.